credentials:
  username: matthaiosmarkatis@gmail.com
  password: Bakumonsuno45!
search_profiles:
- name: graduate-data-uk
  query: Data
  location: United Kingdom
  geoId: 101165590
  filters:
    distance_km: 15
    date_posted: past_24h
    remote:
    - remote
    - hybrid
    experience:
    - entry_level
    - associate
    job_type:
    - full_time
    low_number_applicants: true
    auto_easy: false
    auto_recommend: false
banned_words:
- business
- support
- executive
- officer
- talent
- specialist
- representative
- speaker
- communication
- consultant
- events
- producer
- Personal
- Assistant
- marketer
- content
- digital
- field
- medical
- clinical
- sales
- account executive
- business development
- sales associate
- sales representative
- sales rep
- inside sales
- outside sales
- sales specialist
- pre-sales
- post-sales
- lead generation
- customer acquisition
- territory manager
- client acquisition
- relationship manager
- solutions consultant
- sales manager
- marketing
- brand manager
- growth manager
- content marketer
- content marketing
- performance marketing
- digital marketing
- social media
- seo specialist
- sem specialist
- campaign manager
- email marketing
- communications specialist
- advertising
- promotion manager
- community manager
- events coordinator
- crm specialist
- crm manager
- customer relationship
- customer success
- customer success manager
- account manager
- retention specialist
- client success
- loyalty manager
- content writer
- content creator
- content strategist
- copywriter
- copywriting
- blogger
- editorial assistant
- influencer marketing
- creative strategist
- content manager
- publishing assistant
- courier
- delivery driver
- delivery associate
- logistics
- logistics coordinator
- shipping coordinator
- supply chain
- distribution manager
- warehouse associate
- fulfillment associate
- manager
- team lead
- supervisor
- regional manager
- operations manager
- general manager
- project manager
- representative
- rep
- account rep
- field representative
- brand ambassador
- territory rep
- area manager
- store manager
- customer service
- client services
- customer support
- helpdesk
- relationship executive
- service advisor
- volunteer
- intern
- internship
- work experience
- apprentice
- apprenticeship
- contractor
- contract role
- temp
- temporary role
- freelance
- freelancer
- seasonal
- service
runtime:
  headless: false
  accept_cookies_selector: button[action-type="ACCEPT"]
  random_delay_ms:
  - 800
  - 2200
  max_tabs: 1
  log_level: INFO
  proxy_pool: []
