credentials:
  username: matthaiosmarkatis@gmail.com
  password: Bakumonsuno45!
search_profiles:
- name: graduate-data-uk
  query: Software,Data,AI,Devops,Machine Learning,Automation,Developer,Python,graduate,junior
  location: United Kingdom
  geoId: 101165590
  filters:
    distance_km: 15
    date_posted: custom_hours
    remote:
    - remote
    - hybrid
    experience:
    - entry_level
    - associate
    job_type:
    - full_time
    low_number_applicants: false
    auto_easy: false
    auto_recommend: true
    date_posted_custom_hours_value: 7
banned_words:
- business
- support
- executive
- product
- english
- HR
- teacher
- teaching
- Human
- invoice
- inspector
- surveyor
- construction
- surveyor
- report
- Resources
- Planning
- Costing
- Employment
- Solicitor
- Support
- Technician
- BC
- Platform
- Lift
- tutor
- manager
- protection
- specialist
- market
- wealth
- finance
- commercial
- lawyer
- experience
- operative
- assurance
- collections
- officer
- recruiter
- recruit
- officer
- principal
- technical
- leading
- maintance
- service
- lead
- chemist
- senior
- executive
- recruitment
- accountant
- pharma
- pharmacy
- bio
- biology
- policy
- talent
- representative
- speaker
- communication
- consultant
- events
- producer
- Personal
- Assistant
- marketer
- content
- digital
- field
- medical
- clinical
- sales
- account executive
- business development
- sales associate
- sales representative
- sales rep
- inside sales
- outside sales
- sales specialist
- pre-sales
- post-sales
- lead generation
- customer acquisition
- estimator
- surveyor
- territory manager
- client acquisition
- relationship manager
- solutions consultant
- sales manager
- marketing
- brand manager
- growth manager
- content marketer
- content marketing
- performance marketing
- digital marketing
- social media
- sem specialist
- campaign manager
- email marketing
- communications specialist
- advertising
- promotion manager
- community manager
- events coordinator
- crm specialist
- crm manager
- customer relationship
- customer success
- customer success manager
- account manager
- retention specialist
- client success
- loyalty manager
- content writer
- content creator
- content strategist
- copywriter
- copywriting
- blogger
- editorial assistant
- influencer marketing
- creative strategist
- content manager
- publishing assistant
- courier
- delivery driver
- delivery associate
- logistics
- logistics coordinator
- shipping coordinator
- supply chain
- distribution manager
- warehouse associate
- fulfillment associate
- manager
- team lead
- supervisor
- regional manager
- operations manager
- general manager
- project manager
- representative
- rep
- account rep
- field representative
- brand ambassador
- territory rep
- area manager
- store manager
- customer service
- client services
- customer support
- helpdesk
- relationship executive
- service advisor
- volunteer
- intern
- internship
- work experience
- apprentice
- apprenticeship
- contractor
- contract role
- temp
- temporary role
- freelance
- freelancer
- seasonal
- service
runtime:
  headless: false
  accept_cookies_selector: button[action-type="ACCEPT"]
  random_delay_ms:
  - 800
  - 2200
  max_tabs: 1
  log_level: INFO
  proxy_pool: []
